# mongo db pod creating one replica
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbpod
  labels:
    app: mongolabel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongolabel
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongolabel
    spec:
      containers:
      - name: mongo
        image: lerndevops/samples:mongodb

#defining service object of type clusterIP for mongodbpods #
--- 
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


#deploying spring boot app image from docker lerndevops/samples:springboot-app  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springapp
    spec:
      containers:
      - name: springboot-app
        image: lerndevops/samples:springboot-app

#adding nodeport for frontend app
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-svc
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 8080
  selector:
    app: springapp

